---
- name: Installing metricbeat
  apt:
    name:
      - metricbeat
    update_cache: yes
    state: latest
  when: ansible_distribution == "Debian" and ansible_distribution_release == "buster"

- name: Installing metricbeat
  yum:
    name:
      - metricbeat
    state: latest
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
