---
- name: Adding nginx repo
  template:
    src: ../templates/centos-repo.j2
    dest: /etc/yum.repos.d/nginx.repo
    mode: 0664
    owner: root
    group: root
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: Installing nginx
  yum:
    name:
      - nginx
    state: latest
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"