---
- name: Importing PGP key 
  raw: wget -qO - https://nginx.org/keys/nginx_signing.key | apt-key add -
  args:
    executable: /bin/bash
  when: ansible_distribution == "Debian" and ansible_distribution_release == "buster"

- name: Adding nginx repo
  template:
    src: ../templates/debian-repo.j2
    dest: /etc/apt/sources.list.d/nginx.list
    mode: 0664
    owner: root
    group: root
  when: ansible_distribution == "Debian" and ansible_distribution_release == "buster"

- name: Installing nginx
  apt:
    name:
      - nginx
    state: latest
    update_cache: yes
  when: ansible_distribution == "Debian" and ansible_distribution_release == "buster"