---
mySubnet:
    Type: "AWS::EC2::Subnet"
    Properties:
        VpcId: 
            Ref: "VPC"
    CidrBlock: "10.0.0.0/24"
    AvailabilityZone:
        Fn::Select:
            - "0"
            - "Fn::GetAZs": ""