---
- name: Install packages requirement
  yum:
    name:
      - epel-release
      - bash-completion
      - wget
    state: latest

# - name: Disable SELinux
#   selinux:
#     state: disabled

# - name: Adding pubkey
#   block:
#     - name: Create .ssh directory
#       file:
#         path: ~/.ssh
#         state: directory
#         mode: 0750
#         owner: root
#         group: root
#     - name: Adding pubkey
#       template:
#         src: ../templates/pubkey.j2
#         dest: ~/.ssh/authorized_keys
#         mode: 0600
#         owner: root
#         group: root

# - name: Aliasing ls command
#   lineinfile:
#     path: /etc/profile
#     regexp: 'alias ls'
#     insertafter: 'EOF'
#     state: present
#     line: alias ls='ls --color=auto'

- name: Changing history size
  blockinfile:
    path: /root/.bash_profile
    insertafter: "EOF"
    block: |
      export HISTSIZE=
      export HISTFILESIZE=

# - name: Changing hostname
#   command: /usr/bin/hostnamectl set-hostname "{{ name }}"

    