---
- name: Install packages requirement
  apt:
    name:
      - bash-completion
      - gnupg2
      - python-apt
      - wget
    update_cache: yes
    state: latest


- name: Aliasing ls command
  lineinfile:
    path: /etc/profile
    regexp: 'alias ls'
    insertafter: 'EOF'
    state: present
    line: alias ls="ls --color=auto"


- name: Changing history size
  blockinfile:
    path: /root/.profile
    insertafter: "EOF"
    block: |
      export HISTSIZE=
      export HISTFILESIZE=


# - name: Changing hostname
#   command: /usr/bin/hostnamectl set-hostname "{{ name }}"


    
