---
- name: install package requirement
  yum:
    name:
      - wget
      - net-tools
      - bind-utils
      - yum-utils
      - iptables-services
      - bridge-utils
      - bash-completion
      - kexec-tools
      - sos
      - psacct
      - epel-release
    state: latest
  
- name: install base package
  yum:
    name:      
      - ansible
      - pyOpenSSL
      - python-cryptography
      - python-lxml
    state: latest
    enablerepo: epel

- name: change hostname master
  hostname:
    name: "{{ master_hostname }}"
  when: ansible_facts['default_ipv4']['address'] == "{{ master_ip }}"
- name: change hostname node1
  hostname:
    name: "{{ node1_hostname }}"
  when: ansible_facts['default_ipv4']['address'] == "{{ node1_ip }}"
- name: change hostname infra
  hostname:
    name: "{{ infra_hostname }}"
  when: ansible_facts['default_ipv4']['address'] == "{{ infra_ip }}"

- name: change /etc/hosts file
  blockinfile:
    path: /etc/hosts
    insertafter: "EOF"
    block: |
      {{ master_ip }}  master  {{ master_hostname }}
      {{ node1_ip }}   node1   {{ node1_hostname }}
      {{ infra_ip }}   infra   {{ infra_hostname }}

- name: install docker
  yum:
    name: 
      - docker-1.13.1
    state: latest

- name: change /etc/hosts file
  blockinfile:
    path: /etc/sysconfig/docker-storage-setup
    insertafter: "EOF"
    block: |
      DEVS=/dev/sdb
      VG=docker-vg











    
