---
- name: Updating zone file
  template:
    src: ../templates/db.j2
    dest: /etc/bind/zones/db.test.co.th
    mode: 0640
    owner: root
    group: bind


- name: Updating option file
  template:
    src: ../templates/named.conf.options.j2
    dest: /etc/bind/named.conf.options
    mode: 0640
    owner: root
    group: bind

- name: Reloading config
  command: /usr/sbin/rndc "{{ item }}"
  with_items:
    - reload
