---
- name: install package requirement
  dnf:
    name:
      - bash-completion
      - wget
    state: latest

- name: creating ELK 7.5 repo 
  block:
    - name: ES repository
      template:
        src: ../templates/elastic-centos.j2
        dest: /etc/yum.repos.d/elastic.repo
        mode: 0664
        owner: root
        group: root
    # - name: Kibana repository
    #   template:
    #     src: ../templates/kibana-centos.j2
    #     dest: /etc/yum.repos.d/kibana.repo
    #     mode: 0664
    #     owner: root
    #     group: root

- name: Importing PGP key
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
  tags: pgpkey

- name: Install elasticsearch
  dnf:
    name:
      - elasticsearch
    state: latest

# - name: install Kibana 
#   dnf:
#     name:
#       - kibana
#     state: latest

# - name: install Nginx
#   dnf:
#     name:
#       - nginx
#     state: latest


